### ISSUE TITLE
web support static_file

### ISSUE THREAD

**Issue by luover** [ntex-rs/ntex#10]
hi, I try to writer a web app, I find ntex::web doesn't support static_file, i think that it's basic functions for webapp dev.
thanks.

**Comment by fafhrd91** [comment]
actix-files could be ported. I am, personally, don’t use static files.

**Comment by luover** [comment]
there is problem, actix-http header has some customize part don't become in ntex::http header,
so if port from it, I think should change or add some code to ntex::http header?

**Comment by fafhrd91** [comment]
You try hyperx create, it should provide all required headers

**Comment by luover** [comment]
ok, thanks.
