### ISSUE TITLE
Regex in url

### ISSUE THREAD

**Issue by leon3s** [ntex-rs/ntex#113]
Hi there,

Im sorry if it's a noob question. But on actix you have the possibility to match all path using that kind of method

```rust
#[get("foo/{bar}/{tail:.*}")]
```
where it will match
```
foo/1/2/           -> Params {'bar': '1', 'tail': '2/'}
foo/abc/def/a/b/c  -> Params {'bar': 'abc', 'tail': 'def/a/b/c'}
```

And it's seems not working on ntex i wonder if it's intended or if it's a bug.
If it's intended do you have a workarround to match this use case ?

Thank you for your time!

**Comment by fafhrd91** [comment]
does it work with 

```
#[get("foo/{bar}/{tail}*")]
```

**Comment by leon3s** [comment]
It's working like a charm thank you a lot for your reactivity!

Can i make a pull request in the example repository inside the basic directory with this example ?

**Comment by fafhrd91** [comment]
sure
