### ISSUE TITLE
TechEmpower benchmark startup problems

### ISSUE THREAD

**Issue by clia** [ntex-rs/ntex#119]
The final preview run is happening now on tfb-status: [Run ID: dbde77c0-3a66-491d-9698-8b075e29baa8](https://tfb-status.techempower.com/results/dbde77c0-3a66-491d-9698-8b075e29baa8)

[[ntex-db]](https://tfb-status.techempower.com/unzip/results.2022-06-21-06-04-27-995.zip/ntex-db) had problems starting or stopping
[[ntex-db-astd]](https://tfb-status.techempower.com/unzip/results.2022-06-21-06-04-27-995.zip/ntex-db-astd) had problems starting or stopping

**Comment by fafhrd91** [comment]
[tfb pr](https://github.com/TechEmpower/FrameworkBenchmarks/pull/7439) should fix the problem
