### ISSUE TITLE
[glommio] does it work?

### ISSUE THREAD

**Issue by kolbma** [ntex-rs/ntex#141]
Hello,
does using __glommio__ instead of __tokio__ currently work?

I've tried to use it, but it throws an exception in the `ntex::main` macro.  
Can't remember exactly right now, but something with _Incorrect Source Type_.

Do I miss anything to get it to work with __glommio__ or should it be a drop-in replacement for __tokio__?  
There is no _example_ or _test_ where __glommio__ would be used with __ntex__. Only the _README_ points to it...

**Comment by fafhrd91** [comment]
it does work.
