### ISSUE TITLE
Breaking change on State with new version 0.5.30

### ISSUE THREAD

**Issue by leon3s** [ntex-rs/ntex#147]
Hey there.
Im experiencing a problem where i was using `State::new` to initialize a variable because im using `web::types::State<Pool>`
in all my functions. But since the new version it's seems not working anymore and doesn't have equivalent.
Is it possible to programatically create a `State<T>` or you don't plan to reintroduce the feature ?
Kinda make me change a lot of code but it is how it is.

**Comment by fafhrd91** [comment]
sorry about change, didnt expect people uses ntex.

just put pool to state directly, App::state(pool)
and access it via State<Pool> in handler

**Comment by fafhrd91** [comment]
did it help?

**Comment by leon3s** [comment]
@fafhrd91 Sorry i didn't expected a reply that fast.

Also idk if it's me but i don't have any notification that you replied or even closed the issue.
I don't have problem to use it inside handlers. I was using the `State<Pool>` before i construct the server to do some setups on my database and since i already had some function that was called inside handlers that take `State<Pool>` as parameters i created a temporary `State<Pool>` using `web::types::State::new`.
So i guess that mean you don't want us to use a `State<T>` outside of handlers ?

This is a example of my messy code maybe it will be better then my explanation:

```
let name = "default";
let s_pool = web::types::State::new(pool.to_owned());
repositories::namespace::inspect_by_name(name.to_owned(), pool).await {
    Err(_err) => {
      let new_nsp = NamespacePartial {
        name: name.to_owned(),
      };
      repositories::namespace::create(new_nsp, pool).await?;
      Ok(())
    }
    Ok(_) => Ok(()),
  }
```

**Comment by fafhrd91** [comment]
do not change handlers, just dont use State when you set pool to an App

**Comment by leon3s** [comment]
I think we are misunderstanding and this is because of my poor english sorry.
I wont bother you more i'll just change all my code.

**Comment by fafhrd91** [comment]
fyi, here is example 

https://docs.rs/ntex/0.5.30/ntex/web/struct.App.html#method.state

**Comment by leon3s** [comment]
I know, i also saw all your examples.
I don't open issue for fun.
My problem came from how i splited my code.
I have helper function that i reuse outside of handlers. That take a `State<Pool>` as parameters.
And you removed the ability to have a `State<T>` outside of handlers by removing the `State::new` method.

I believe code is better than explanation so maybe it will be more clear with this:
https://github.com/nxthat/nanocld/blob/nightly/src/repositories/cargo.rs
https://github.com/nxthat/nanocld/blob/nightly/src/services/cargo.rs

But as i said before the problem came from how i splited my code.
I just didn't expected that kind of breaking change for a minor update.
So i wanted to know if you think to reimplement the features or not.
And the answer seems to be no and im fine with it.

**Comment by leon3s** [comment]
Yeah that is the fix i would like to no do because i'll have to rewrite all function inside `repositories` directory.
And then rewrite how i call them.
But as i said it is how it is.

**Comment by leon3s** [comment]
Anyway thanks to have took the time to reply and look into my code.
I hope your eyes aren't bleeding.
I wish you a nice day or night.

**Comment by fafhrd91** [comment]
you can use `Arc<Pool>`, this what was State before, but you would need to change handlers to accept`State<Arc<Pool>>`
