### ISSUE TITLE
Feature request: Callback for each new connection (on_connect method)

### ISSUE THREAD

**Issue by khvzak** [ntex-rs/ntex#179]
Actix-web support [`HttpServer::on_connect`](https://docs.rs/actix-web/4.3.0/actix_web/struct.HttpServer.html#method.on_connect) handler which is called on a new connection.
This method is useful for various cases including getting tls connection info (eg. client certificate). 
[Example](https://github.com/actix/examples/blob/master/https-tls/rustls-client-cert/src/main.rs)

Is there any alternative available for ntex?

**Comment by fafhrd91** [comment]
you get cert from handler. 

you can get ioref object from request, https://docs.rs/ntex/0.6.3/ntex/web/struct.HttpRequest.html#method.io

and then use query api, https://docs.rs/ntex/0.6.3/ntex/io/struct.IoRef.html#method.query

https://github.com/ntex-rs/ntex/blob/a1690d7b343b96ea2feb8f4b50d5563a8dfad59b/ntex-tls/src/openssl/mod.rs#L18

**Comment by khvzak** [comment]
Thanks!
