### ISSUE TITLE
WASI tokio ntex-rt implementation

### ISSUE THREAD

**Issue by botika** [ntex-rs/ntex#194]
I was bored and was looking to implement rpc in wasm to use them over legacy modules in nodejs. I think it would not be difficult to implement in `ntex-rt`, it basically has the same interface, https://crates.io/crates/wasi-tokio . If you give me the ok, I can do it

**Comment by fafhrd91** [comment]
I wouldn't mind, but problem is that is increases maintenance burden. I would prefer to find out way how we can extract rt integrations to separate crates

**Comment by fakeshadow** [comment]
It's better to follow the progression of  `std::os::wasi` instead of using some fork of `hyper`. rushing to support a not yet finalized standard is not a bright idea.

**Comment by botika** [comment]
Ok, much better. Thanks! I close that
