### ISSUE TITLE
Documentation Site Down

### ISSUE THREAD

**Issue by Ahmard** [ntex-rs/ntex#217]
Hello Ntex,
I was trying to visit Ntex docs site and noticed it went down
URL: https://ntex.rs/
Please check.

Thanks.

**Comment by fafhrd91** [comment]
@leon3s could you check, seems ntex.rs points to host that doesn't work

**Comment by leon3s** [comment]
Sorry for that it will be fixed i'm working on it

**Comment by Ahmard** [comment]
Okay, Leon.
Thank you guys for your prompt response.

**Comment by leon3s** [comment]
Nice timing @Ahmard it's fixed and updated to latest ntex version!

**Comment by Ahmard** [comment]
Noted @leon3s, checking..
Thank you once again

**Comment by fafhrd91** [comment]
@leon3s could you check doc site, seems down again
