### ISSUE TITLE
Experiencing a timeout while uploading a large file

### ISSUE THREAD

**Issue by leon3s** [ntex-rs/ntex#245]
Hey, i'm not sure it's a ntex issue it may come from my implementation.

This is my [server code](https://github.com/nxthat/nanocl/blob/ac5cd75964a3797177cd0ce8b703d5121eef8b4b/bin/nanocld/src/services/vm_image.rs#L45)
and my [client code](https://github.com/nxthat/nanocl/blob/ac5cd75964a3797177cd0ce8b703d5121eef8b4b/bin/nanocl/src/commands/vm_image.rs#L34)

I feel that come from ntex http client when using a send stream, the timeout is not reset after each successful write.
Please, let me know if I'm correct or not.

**Comment by fafhrd91** [comment]
what version of ntex do you use?

**Comment by leon3s** [comment]
The latest i just run a cargo update

**Comment by fafhrd91** [comment]
is timeout on client or server side?

**Comment by fafhrd91** [comment]
could you also try to create executable example

**Comment by leon3s** [comment]
I think it's on client side, this is the error message i get: `Timeout while waiting for response`
It pop after 3 seconds witch is the default timeout for the client.
I suspect it come from this [code](https://github.com/ntex-rs/ntex/blob/2a19b7f995fb9120e1390aff2369ac6b4044fc48/ntex/src/http/client/sender.rs#L78)

If you don't mind to try in my project, you can clone it do a `docker-compose up` and run a `cargo make run-cli vm image create test ./jammy-server-cloudimg-amd64.img` this is the [image](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img) or else i can make a small repo to reproduce the bug.

**Comment by fafhrd91** [comment]
ok, I will check

**Comment by leon3s** [comment]
Thank you

**Comment by leon3s** [comment]
I created a minimal repository to avoid you any problem actually, or long build time you can find it [there](https://github.com/leon3s/ntex-timeout)

**Comment by fafhrd91** [comment]
could you try #247

**Comment by leon3s** [comment]
Look like it working in both my project and the test repository, thanks for your time!
