### ISSUE TITLE
Add try_join to ntex_utils

### ISSUE THREAD

**Issue by GPeaky** [ntex-rs/ntex#259]
Hi there, i don't known if use tokio::try_join!(), because of the ntex:rt. in case that i can't. i would like to request the try_join(), function because rigth now am doing something like this

```rust
        let (db_result, cache_result) = join(update_user_task, del_cache_task).await;

        db_result?;
        cache_result?;
``` 

and it's a bit weird

**Comment by fafhrd91** [comment]
tokio::try_join!() should work fine

**Comment by GPeaky** [comment]
okay, and just i noob question. is possible to use tokio::try_join!(), if the result types are different?

Result Types AppError and Error(external crate). And i can't use try_join!() because the result types are different. But i implemented ```From<Error> for AppError```, exist some way to do it? i have been searching for 1 hour and i didn't find anything. Sorry to ask this :(

```rs
let delete_cache_future = self.cache.user.delete(id); // Returns AppError
let update_user_future = conn.execute(&cached_statement, &params[..]); // Returns Error

tokio::try_join!(update_user_future, delete_cache_future); // Error. Different error types
```

**Comment by fafhrd91** [comment]
you should ask tokio devs, or read tokio docs.

**Comment by GPeaky** [comment]
okay, thanks for your time!
