### ISSUE TITLE
SSE integration

### ISSUE THREAD

**Issue by GPeaky** [ntex-rs/ntex#268]
Hi, ntex have support for Server Side Events? and if it's not is there any plan of implement it?

**Comment by GPeaky** [comment]
Or Http2 Streams (sorry i am a noob 😞)

**Comment by leon3s** [comment]
Hey yes, both are supported I believe for SSE you can look at [here](https://github.com/ntex-rs/examples/tree/master/server-sent-events)

**Comment by fafhrd91** [comment]
sse does not require any specific implementation

**Comment by fafhrd91** [comment]
http2 streams are supported as well

**Comment by GPeaky** [comment]
Is there any example of streams? SSE only supports text and i need to send binary data. And thanks for the response :)

**Comment by fafhrd91** [comment]
same example as for sse, just change response content-type and make sure you connects with http2 client
