### ISSUE TITLE
Websocket: second message got delayed if client sends two messages to server simultaneously.

### ISSUE THREAD

**Issue by xudesheng** [ntex-rs/ntex#27]
when WebSocket's client sends two messages simultaneously, the second message would got delayed.
How to reproduce, use: [examples/websocket/client](https://github.com/ntex-rs/examples/blob/master/websocket/src/client.rs)
original code(line 55-58):
```
        // send text to server
        if futures::executor::block_on(tx2.send(ws::Message::Text(cmd))).is_err() {
            return;
        }
```
replace it with new demo code:
```
       // send text to server
        let cmdback=cmd.clone();
        if futures::executor::block_on(tx2.send(ws::Message::Text(cmd))).is_err() {
            return;
        }
        if cmdback=="test\n"{
            println!("We are going to send second one...");
            let cmd = format!("No more test!\n");
            if futures::executor::block_on(tx2.send(ws::Message::Text(cmd))).is_err() {
                return;
            }
        }
```
Expected Result:
If I enter "test", then it should print two lines: one is "test" and another one is "No more test!".

Actual result:
The line for "No more test!" would only be printed when the client receives a Ping from the server or you enter next.
```
demo
Server: b"demo\n"
test
We are going to send second one...
Server: b"test\n"
Got server ping: b""
Server: b"No more test!\n"
test
We are going to send second one...
Got server ping: b""
Server: b"test\n"
demo
Server: b"No more test!\n"
test
We are going to send second one...
demo
```

Not sure this issue is similar to [issue 384:](https://github.com/actix/actix/pull/384) or not. The second message would be lost quietly in Actix but it's just got delayed here.

When I use the same code to talk with **Tungstenite** based echo server, the issue doesn't appear.

**Comment by fafhrd91** [comment]
fixed in master
