### ISSUE TITLE
Please respect semantic versioning

### ISSUE THREAD

**Issue by xmeta** [ntex-rs/ntex#298]
It seems that version 1.1 is no longer backward compatible with 1.0.

The following changes broke [ntex-multipart](https://github.com/ntex-rs/ntex-extras/tree/master/ntex-multipart)

* Rename [ParseError](https://docs.rs/ntex/1.0.0/ntex/http/error/enum.ParseError.html) to [DecodeError](https://docs.rs/ntex/latest/ntex/http/error/enum.DecodeError.html)

Please refer to [SemVer](https://semver.org/#spec-item-8)

> Major version X (X.y.z | X > 0) MUST be incremented if any backward incompatible changes are introduced to the public API. It MAY also include minor and patch level changes. Patch and minor versions MUST be reset to 0 when major version is incremented.

**Comment by fafhrd91** [comment]
new ntex-multipart got releaesed
