### ISSUE TITLE
`ntex::time::timeout` is not accurate

### ISSUE THREAD

**Issue by khvzak** [ntex-rs/ntex#310]
An example:
```rust
#[ntex::main]
async fn main() -> Result<(), ()> {
    let fut = async {
        ntex::time::sleep(ntex::time::Millis(15)).await;
        1
    };
    let res = ntex::time::timeout(ntex::time::Millis(10), fut).await;
    println!("{res:?}");
    Ok(())
}
```

prints `Ok(1)` but should print `Err(())`.
ntex latest v1.1.2, macOS x86_64 14.3, `tokio`.

Same example using `tokio::time` works fine.

**Comment by fafhrd91** [comment]
main purpose of the ntex timer is network timeouts and those usually within seconds

**Comment by khvzak** [comment]
Thanks for confirming!
