### ISSUE TITLE
[Bug] Unable to set length manually

### ISSUE THREAD

**Issue by nanakura** [ntex-rs/ntex#317]
I noticed that ntex will automatically calculate Content-Length, but even if there is .content_length() api, it will not have any effect.
How to set the Content-Length manually
```rust
use ntex::web;

#[web::get("/")]
async fn hello() -> impl web::Responder {
    web::HttpResponse::Ok().content_length(1000).finish()
}
#[ntex::main]
async fn main() -> std::io::Result<()> {
    web::HttpServer::new(|| {
        web::App::new()
            .service(hello)
    })
        .bind(("127.0.0.1", 8080))?
        .run()
        .await
}

```

response:
```
http GET http://localhost:8080/
HTTP/1.1 200 OK
content-length: 0
date: Wed, 27 Mar 2024 14:50:41 GMT
```

**Comment by fafhrd91** [comment]
why do you need this?

what should be ntex behavior in your example? ntex supports pipelining, but if your example would be allowed it would broke pipelining.

**Comment by nanakura** [comment]
> why do you need this?
> 
> what should be ntex behavior in your example? ntex supports pipelining, but if your example would be allowed it would broke pipelining.

```rust
use futures::future::ok;
use futures::stream::once;
use ntex::util::Bytes;
use ntex::web;

#[web::get("/")]
async fn hello() -> impl web::Responder {
    let body = once(ok::<_, web::Error>(Bytes::from_static(b"something of unpredictable length")));
    web::HttpResponse::Ok().content_length(1000).streaming(body)
}
#[ntex::main]
async fn main() -> std::io::Result<()> {
    web::HttpServer::new(|| {
        web::App::new()
            .service(hello)
    })
        .bind(("127.0.0.1", 8080))?
        .run()
        .await
}

```

In this case `.content_length()` also does not work

response：

```
HTTP/1.1 200 OK
date: Thu, 28 Mar 2024 00:43:40 GMT
transfer-encoding: chunked

something of unpredictable length
```

I want to know an example where  `.content_length()`  works

**Comment by fafhrd91** [comment]
you can try Body::Stream and this method https://docs.rs/ntex/latest/ntex/http/struct.ResponseHead.html#method.no_chunking

**Comment by nanakura** [comment]
> you can try Body::Stream and this method [docs.rs/ntex/latest/ntex/http/struct.ResponseHead.html#method.no_chunking](https://docs.rs/ntex/latest/ntex/http/struct.ResponseHead.html#method.no_chunking)

got it
