### ISSUE TITLE
Moving websocket to a feature

### ISSUE THREAD

**Issue by SVilgelm** [ntex-rs/ntex#319]
The ntex is a great library and we decided to use it within Microsoft. The only issue is our Component Governance system raises an alert due to the dependency on `sha1` crate.

the `sha1` is used in the two places only:
- https://github.com/ntex-rs/ntex/blob/4ed6712ac4622d6fd7f76f48fa6a2a5b7a4caa19/ntex/src/ws/client.rs#L227
- https://github.com/ntex-rs/ntex/blob/4ed6712ac4622d6fd7f76f48fa6a2a5b7a4caa19/ntex/src/ws/handshake.rs#L73

So, would it be possible to create a feature for `ws` module? I understand that this will break backward compatibility, but the fix will be very simple (add feature to `Crate.toml`) for any current consumers.

**Comment by fafhrd91** [comment]
should we discuss this within Microsoft?

**Comment by fafhrd91** [comment]
my alias nikki

**Comment by SVilgelm** [comment]
it would be great if you can join this conversation: https://teams.microsoft.com/l/message/19:7b99f7fc8b0946e6a5e9797e4442c3cc@thread.tacv2/1711565973382?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=a4f716cc-3291-4989-a4bb-a66143117f4f&parentMessageId=1711565973382&teamName=Oxidizer&channelName=%F0%9F%9B%9F%20Support&createdTime=1711565973382

**Comment by fafhrd91** [comment]
ntex v1.2.1 is released
