### ISSUE TITLE
Is there a feature comparison with other frameworks ?

### ISSUE THREAD

**Issue by jreuben11** [ntex-rs/ntex#344]
I recently learned the Tokio ecosystem - Axum, Tonic, Hyper, Tonic, and am delving into Pavex. 
How does this compare ?
As a software engineer, I would pick the optimal framework - so if you can provide a list of advantages, it would go a long way in influencing crate selection choice.

**Comment by fafhrd91** [comment]
you should use something more popular, chanes to get help much higher.

this question is for discussions it is nit an issue
