### ISSUE TITLE
The `insert` method for `Extensions` does not return existed value

### ISSUE THREAD

**Issue by photino** [ntex-rs/ntex#345]
The docs for [`insert`](https://docs.rs/ntex/latest/ntex/util/struct.Extensions.html#method.insert) says that 

> If a extension of this type already existed, it will be returned.

But it does not. The function signature should be 
```rust
pub fn insert<T>(&mut self, val: T) -> Option<T>
where
    T: 'static,
```

**Comment by fafhrd91** [comment]
fixed
