### ISSUE TITLE
Compilation failed for windows

### ISSUE THREAD

**Issue by tryor** [ntex-rs/ntex#346]
failed to run custom build command for `aws-lc-sys v0.15.0`

ntex version:
ntex = { version = "=1.2.1", features = ["tokio", "rustls"] }

tool chain：
    1.76-x86_64-pc-windows-msvc

What can be done to solve this problem? Thanks

**Comment by fafhrd91** [comment]
this error is from rustls crate. you need cmake and nasm, also check rustls docs

**Comment by tryor** [comment]
Thanks for your prompt reply, I'll give it a try.
