### ISSUE TITLE
Help: How to clone payload in  this middleware code from ntex-rs examples

### ISSUE THREAD

**Issue by Chacix** [ntex-rs/ntex#391]
https://github.com/ntex-rs/examples/blob/a3cb7646348f0ba25efffc639125eec766860368/middleware/src/read_request_body.rs#L44

Here, you can indeed read the body generated by the payload, and since this is mutable (meaning it has ownership), after calling    let mut stream = req.take_payload(), the request will no longer have ownership of the payload. For example, if you call the serviceFactory like:

async fn update_by_id(
    id: Path<i32>, 
    update_data: Json<(String, i32)>, 
    db: State<Pool<Postgres>>, 
    req: HttpRequest
) -> Result<HttpResponse, HttpResError> {

This update_data Json<(String, i32)> will cause a deserialization error.
I guess the payload field ownership had been taken
I try a lot to clone payload and still don't work, So how to clone the payload in this middleware 

actually, I want this middleware to print both body(request and response body)

example code from node.js :)
<img width="1324" alt="image" src="https://github.com/user-attachments/assets/469933d2-ef64-40e9-9eb6-092794eab0df">

**Comment by fafhrd91** [comment]
there is [set_payload()](https://docs.rs/ntex/latest/ntex/web/struct.WebRequest.html#method.set_payload) method
