### ISSUE TITLE
Added support for HTTP3

### ISSUE THREAD

**Issue by Web-Coke** [ntex-rs/ntex#392]
Hello!

The HTTP3 protocol has been around for a long time, and it has been a discouragement for many people. 

As the best and fastest HTTP framework in Rust, can you consider supporting HTTP3?

**Comment by fakeshadow** [comment]
You can reference https://github.com/orgs/ntex-rs/discussions/352
http/3 is basded on quic transport which utilize UDP sockets.

**Comment by Web-Coke** [comment]
Ok, thanks for the answer!
