### ISSUE TITLE
not all workers are shutdown, and wait indefinitely when send SIGTERM signal

### ISSUE THREAD

**Issue by gftea** [ntex-rs/ntex#403]
I encounter an issue when kill the server, not all workers are shutdown according to ntex logs,

so the await for `Server<Connection>` never return

version is 2.1.0

**Comment by gftea** [comment]
It is not easy to reproduce because it happen in a long running service, but according to the codes, there is 30seconds timeout when shuting down, 
I do see log `log::info!("SIGTERM received, stopping");`
then  some workers hit `    log::info!("Worker {:?} has been stopped", id);`
while can not it seems other worker stop futuer never scheduled?

**Comment by fafhrd91** [comment]
if this still the issue, could you try ntex v2.5.0
