### ISSUE TITLE
Serious Performance Regression During Q3 2024 for Data Updates Test on TechEmpower

### ISSUE THREAD

**Issue by mkvalor** [ntex-rs/ntex#421]
Summary: Data Updates test regression of ntex at some point after July, 2024

I noticed a serious performance regression by ntex in the Data Updates portion of periodic automated runs of the famous Tech Empower suite during the 3rd quarter of this year.  I offer the below details as a "friend of the repo" to the dev team.  (my current work does not actually involve building or running ntex)  You can find the web listing of all automated TechEmpower test runs at:
https://tfb-status.techempower.com/

(Baseline) On the test run that started July 10, 2024, we see high performance from ntex in the "Data Updates" test results, as expected.  This has been the case for all these test runs, for over two years (exept for previous brief ntex performance regressions):
https://www.techempower.com/benchmarks/#section=test&runid=6685e0dd-0767-4c83-950a-a8c78c895d0e&hw=ph&test=update
In the results linked above:
* "ntex [tokio,db]" has the 7th best performance score, at 58,058 rps (98.1% of the highest score).
* "ntex [async-std,db]" has the 10th best performance score, at 57,710 rps (97.5% of the highest score).
* Similar ranks and high performance are replicated for an additional 3 automated test runs after this one, until the one that started on August 4.

Starting with the test run that began on August 4, we see a huge perfromance regression in the Data Updates test results:
https://www.techempower.com/benchmarks/#section=test&runid=b0a928a6-ff24-462e-8445-fa2dc1bbc7ee&hw=ph&test=update
* "ntex [async-std, db]" has the 117th best performance score, with only 19,971 rps (34.0% of the highest score)
* "ntex [tokio, db]" has the 144th best performance score, with only 17,509 rps (29.8% of the highest score)
* None of the other frameworks usually found in the top 20 results of this test regressed in performance like ntex did, and all of these other ones maintain their rps results in the high 50K range.

The above terrible results -- serving fewer than half of the previously reported 'requests per second' -- are repeated for 6 additional recent test runs, including the most recent one that ran a week ago, on Septenber 11. (there is a new run in progress which started this week)

**Comment by jiafuzhang** [comment]
I just went to see it.  There seems to be a real problem.

**Comment by fafhrd91** [comment]
this is fixed in last run. this was db related problem
