### ISSUE TITLE
how to use the appstate in application 

### ISSUE THREAD

**Issue by livingca** [ntex-rs/ntex#424]
hello,how to use the appstate in application service code or everywhere ,not only in the interface's References,think you

**Comment by fafhrd91** [comment]
you can use [app_state()](https://docs.rs/ntex/latest/ntex/web/struct.WebRequest.html#method.app_state) method

**Comment by livingca** [comment]
> you can use [app_state()](https://docs.rs/ntex/latest/ntex/web/struct.WebRequest.html#method.app_state) method

think you ,I will try it
