### ISSUE TITLE
Is it possible to select `ring` instead of `aws-lc-rs` inside `rustls`

### ISSUE THREAD

**Issue by evshary** [ntex-rs/ntex#428]
`rustls` supports both `ring` and `aws-lc-rs`.
Although it decides to use `aws-lc-rs` by default, it still provides features for users to choose `ring`.
https://github.com/rustls/rustls?tab=readme-ov-file#platform-support

It would be great if `ntex` could provide such an option for users to choose from since some people face the issue while using `aws-lc-rs`, for example, https://github.com/rustls/rustls/issues/1913

**Comment by fafhrd91** [comment]
i think ntex could use “default-features = false”, then you can select right feature in your code.

**Comment by fafhrd91** [comment]
changed in ntex-v2.6.0

**Comment by evshary** [comment]
@fafhrd91 Thanks for your fast update. I've verified it and it works on my side!
