### ISSUE TITLE
Compilation Error when Switching from tokio to glommio in ntex 2.6.0

### ISSUE THREAD

**Issue by pionoor** [ntex-rs/ntex#436]
## Description
When switching from the `tokio` feature to the `glommio` feature in ntex 2.6.0, the crate fails to compile due to unresolved imports and missing functions.

## Cargo.toml Configuration
```toml
[dependencies]
ntex = { version = "2.6.0", features = ["glommio", "compress"] }
```

## Error Messages
1. Unresolved import `self::glommio`
2. Cannot find function `spawn` in the crate root (multiple occurrences)
3. Cannot find function `block_on` in the crate root

## Full Error Output
```
error[E0432]: unresolved import `self::glommio`
   --> /Users/noor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.18/src/lib.rs:478:15
    |
478 | pub use self::glommio::*;
    |               ^^^^^^^ could not find `glommio` in the crate root

error[E0425]: cannot find function `spawn` in the crate root
   --> /Users/noor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.18/src/arbiter.rs:117:36
    |
117 |                     let _ = crate::spawn(ArbiterController {
    |                                    ^^^^^ not found in the crate root

// ... (additional similar errors omitted for brevity)

error[E0425]: cannot find function `block_on` in the crate root
   --> /Users/noor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-rt-0.4.18/src/system.rs:135:20
    |
135 |             crate::block_on(Box::pin(async move {
    |                    ^^^^^^^^ not found in the crate root
```

## Environment
- Rust version: (please provide your Rust version)
- OS: (please provide your operating system)

## Steps to Reproduce
1. Create a new Rust project
2. Add the ntex dependency with glommio feature to Cargo.toml
3. Attempt to compile the project

## Expected Behavior
The project should compile successfully with the glommio feature enabled.

## Actual Behavior
The compilation fails with the errors described above.

## Additional Context
This issue occurs when switching from the tokio feature to the glommio feature. It appears that some imports and functions are not properly configured for the glommio runtime.

**Comment by fafhrd91** [comment]
do you use it on linux? do you need specifically glommio?

**Comment by pionoor** [comment]
I have not tried to deploy it to linux env. I was deving on my Mac before pushing. I would expect it to at least compile.
I don't really need glommio but was trying to test if there is any perf gain over tokio.

**Comment by pionoor** [comment]
Thank you for the prompt response, much appreciated.
