### ISSUE TITLE
discord invite link invalid

### ISSUE THREAD

**Issue by yzn-h** [ntex-rs/ntex#448]
the discord invite link in the readme is invalid
this link https://discord.gg/zBNyhVRz
![image](https://github.com/user-attachments/assets/c8e58f24-fcb2-459d-a67a-6dfff93fca1b)

**Comment by fafhrd91** [comment]
its fixed

**Comment by yzn-h** [comment]
@fafhrd91 unfortunately the new link works only for people who are already in the server, the link points to a channel in the server, it needs to be an invite link

this is how to make an invite link the never expires

https://github.com/user-attachments/assets/f626ff19-f607-4854-a13d-c63a61299dfb

**Comment by fafhrd91** [comment]
thanks! fixed
