### ISSUE TITLE
Is the docs up to date ?

### ISSUE THREAD

**Issue by call-me-q** [ntex-rs/ntex#465]
I went to the site and I see [here](https://ntex.rs/docs/getting-started) that it's still stated 
```
[dependencies]
ntex = { version = "2.0", features = ["tokio"] }
```

while by the time this issue is written, `ntex` already reached `2.8.3`. Given on many `rust` packages has big changes during the development, is it possible that the documentation needs to be updated ?

I'm still new at rust so the documentation site is quite important for me.

**Comment by fafhrd91** [comment]
ntex api is stable within version 2.x, you can use: ntex = "2"

**Comment by call-me-q** [comment]
@fafhrd91 so the documentation pretty much still cover at least almost the whole thing ? If so, thank you :)

**Comment by fafhrd91** [comment]
yes, high level api hasnt change for ling time. documentation is up to date

**Comment by call-me-q** [comment]
@fafhrd91 thank you. Will close this issue then. Thanks for the hard work.
