### ISSUE TITLE
How does a custom tokio runtime work with ntex::rt::System::new().run_local()?

### ISSUE THREAD

**Issue by svanharmelen** [ntex-rs/ntex#468]
I was looking for a solution similar to https://github.com/ntex-rs/ntex/issues/410. It seems to work, but I wondered if things are working as expected...

Asking specifically because when using `#[ntex::main]` I see 2 `ntex-rt:worker:xxx` threads and 3 `ntex-server` threads and no `tokio` worker threads.

When using the above, I notice I now see two `tokio` worker threads, but also I still see the 2 `ntex-rt:worker:xxx` threads and the 3 `ntext-server` threads.

I would somehow expect that those `ntex-rt:worker:xxx` threads would now be replaced by the `tokio` worker threads, but instead it seems to add them.

So in that case, does `ntex` really use the `tokio` worker threads, or does it still spawn all its own worker/tokio threads as well? As in case of the latter, I guess there is not really a reason to run a custom runtime as it seems it's not being used by ntex. Is that correct?

**Comment by fafhrd91** [comment]
ntex-server starts separate thread for each worker and then single threaded tokio runtime. run-local uses existing tokio runtime and still starts separate threads for workers

**Comment by svanharmelen** [comment]
Check, thanks for the info 👍🏻
