### ISSUE TITLE
App state is not configured, to configure use App::state()

### ISSUE THREAD

**Issue by anchalshivank** [ntex-rs/ntex#472]
I’m encountering the following error while trying to run my API server using Ntex:

**Error Message:**
```
App state is not configured, to configure use App::state()
```

I have already configured the application state in my server using `App::state()`, but the error persists. This is my first time using Ntex, and I need assistance resolving this issue.

---

### Code Reference:

Here’s my server setup in the `main.rs` file:  
[[Server Configuration on GitHub](https://github.com/anchalshivank/mt-auth-service/blob/5285ce17a325d16be7d94ade8152857a1915446e/src/main.rs#L34)](https://github.com/anchalshivank/mt-auth-service/blob/5285ce17a325d16be7d94ade8152857a1915446e/src/main.rs#L34)

---

### Image Reference:

![Error Screenshot](https://github.com/user-attachments/assets/698b0803-9629-42c0-ba82-de7866e6b748)

---

### Steps to Reproduce:

1. Clone the repository: [[mt-auth-service](https://github.com/anchalshivank/mt-auth-service)](https://github.com/anchalshivank/mt-auth-service).  
2. Run the server using `cargo run`.  
3. Attempt to hit the `/login` endpoint (or any other relevant endpoint).

---

### Expected Behavior:

The server should process the request and return the appropriate response without errors.

---

### Actual Behavior:

The server throws the error mentioned above when processing the request.

---

### Additional Information:

I was able to successfully add data to my database earlier. However, after refactoring the code to make it cleaner, I encountered this issue.  

---

**Comment by leon3s** [comment]
Heyz it's because on your service /login you try to inject `web::types::State<DbPool>`

And it's seems to not be part of your state anymore, try to load `web::types::State<UserService>` instead

**Comment by anchalshivank** [comment]
Initially, I was passing the pool in the state, but to do that, I had to pass the pool from the controller to the service and then to the repository layer (which was working). To avoid passing the pool across layers, I restructured the code like this, but it is not working. Please help me correct this.

**Comment by leon3s** [comment]
I'll check deeper tomorrow

**Comment by anchalshivank** [comment]
Thanks

**Comment by anchalshivank** [comment]
The error has been fixed as my imports were incorrect , I was not using `use crate::controllers..`, I was directly importing `use controllers::..`, The working code is at [this commit](https://github.com/anchalshivank/mt-auth-service/commit/f7311879aeebe2411db9f4748ed23a1bb6e6ddcc)
