### ISSUE TITLE
Compress middleware Brotli compression not working 

### ISSUE THREAD

**Issue by JeanRomain** [ntex-rs/ntex#488]
Hi
I tested different headers for Accept-Encoding
Gzip, Identity and Deflate compressions are working but Brotli returns the response not compressed
My setup is just the plain :
`App::new()
            .wrap(Compress::new(ntex::http::header::ContentEncoding::Auto))`
or 
`.wrap(Compress::default())`

If I try with 
`App::new()
            .wrap(Compress::new(ntex::http::header::ContentEncoding::Br))`
Then no compression is working at all

**Comment by fafhrd91** [comment]
did you enable brotli festure?

**Comment by JeanRomain** [comment]
Ok it was just that it's working, thanks

**Comment by JeanRomain** [comment]
How to use brotli since 2.12.2?

**Comment by fafhrd91** [comment]
you should take code from previous version and use it directly.

brotli2 crate is unmaintained and there are issues like [this](https://github.com/bitemyapp/brotli2-rs/issues/45), I would advise against using it
