### ISSUE TITLE
An error occurred during the upgrade

### ISSUE THREAD

**Issue by WuJiY** [ntex-rs/ntex#492]
"When I start the application, the following error occurred. What's the reason for this? Is it normal? It seems to have appeared after an upgrade."

Thanks!
![屏幕截图 2024-12-29 224855](https://github.com/user-attachments/assets/f6404d97-cfe9-4239-9ea1-450bb7b1d9a5)

**Comment by fafhrd91** [comment]
it is ok, its just logs. i will update how server logs this

**Comment by WuJiY** [comment]
ok， thanks!

**Comment by fafhrd91** [comment]
ntex-server 2.6.2 fixes this bug
