### ISSUE TITLE
nanorand makes it not compile on CentOS 7

### ISSUE THREAD

**Issue by clia** [ntex-rs/ntex#51]
![CentOS7-not-compile](https://user-images.githubusercontent.com/1589842/122924321-373a7600-d398-11eb-87c1-0db7e07b8fe5.png)
This is because that CentOS 7 lack of `getrandom` syscall, but the nanorand calls it directly.
![nanorand-usage](https://user-images.githubusercontent.com/1589842/122924342-3e618400-d398-11eb-8a48-c68bdb603fd8.png)

I have to import nanorand handy in my project, and add the `getrandom` feature, to make it compiles:
```
nanorand = { version = "0", features = ["getrandom"] }
```

**Comment by fafhrd91** [comment]
i think should be reported upstream.

**Comment by clia** [comment]
nanorand provided a `getrandom` feature, which can avoid this compiling error.
You could use it in ntex, then there's no any error. To find out this error's source costs a lot of time.
A little suggestion. :-)
