### ISSUE TITLE
ntex http client adds `content-length: 0` to GET/HEAD/... requests

### ISSUE THREAD

**Issue by khvzak** [ntex-rs/ntex#56]
Hello! First of all, thanks for the great project.

I noticed that ntex http client adds `content-length: 0` to HTTP/1.1 requests to methods that does not define semantics for request bodies (GET/HEAD/DELETE/TRACE/CONNECT).

According the [RFC7230](https://datatracker.ietf.org/doc/html/rfc7230#page-30):
> A user agent SHOULD NOT send a Content-Length header field when the request message does not contain
   a payload body and the method semantics do not anticipate such a body.

Technically this behavior is valid but not recommented and not all websites respects that.
Is this an expected behavior  or a bug (probably inherited from the actix http client)?

For example, `https://cr.yp.to/` website does not respect such get requests.
```rust
    let client = Client::new();
    let mut response = client
        .get("https://cr.yp.to/")
        .send()
        .await?;

    println!("Response: {:?}", response);
    let body = response.body().await.unwrap();
    let body = String::from_utf8_lossy(&body);
    println!("{}", body);
```

It prints
```
ClientResponse HTTP/1.1 501 Not Implemented
  headers:
    "connection": "close"
    "content-type": "text/html"
    "server": "publicfile"
    "date": "Thu, 26 Aug 2021 13:52:31 GMT"
    "content-length": "52"

<html><body>I do not accept messages</body></html>
```

**Comment by fafhrd91** [comment]
fixed
