### ISSUE TITLE
grpc

### ISSUE THREAD

**Issue by dragon1061** [ntex-rs/ntex#66]
hi  how to use grpc in ntex?

**Comment by botika** [comment]
Well, doing it. You have examples of a [jsonrpc](https://github.com/ntex-rs/examples/tree/master/jsonrpc), just change the protocol.

**Comment by dragon1061** [comment]
ok thanks i will try it

**Comment by botika** [comment]
You can use https://github.com/tokio-rs/prost . But this has nothing to do with an ntex issue. Please close it. If I get bored at some point I will implement grpc although this google protocol is a bit slow.
