### ISSUE TITLE
cannot import dependency?

### ISSUE THREAD

**Issue by phial3** [ntex-rs/ntex#95]
![image](https://user-images.githubusercontent.com/27754514/150121493-cc72bd6c-5a3d-4429-bbeb-4993e2741723.png)

**Comment by fafhrd91** [comment]
it is in readme

```
[dependencies]
ntex = { version = "0.5", features = ["tokio"] }
```

**Comment by phial3** [comment]
> 

i add feature next, is still not ok

``` ["glommio", "tokio", "async-std"]```

**Comment by fafhrd91** [comment]
i don’t understand
